### ISSUE TITLE
Problem when running the app.

### ISSUE THREAD

**Issue by LeChauvet** [alexkarargyris/Caffe_OpenCV_Android_App#3]
Hi, there. I'm trying to run the demo, however when I tried to load image choosing from library, the app stopped running. And the log is as follow:

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=file:///storage/emulated/0/DCIM/Camera/IMG_20160329_210847.jpg typ=image/jpeg }} to activity {com.example.alexandroskarargyris.myapplication/com.example.alexandroskarargyris.myapplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
                                                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:3704)
                                                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3747)
                                                                                                  at android.app.ActivityThread.access$1400(ActivityThread.java:153)
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5432)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
                                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)' on a null object reference
                                                                                                  at com.example.alexandroskarargyris.myapplication.MainActivity.onActivityResult(MainActivity.java:120)
                                                                                                  at android.app.Activity.dispatchActivityResult(Activity.java:6508)
                                                                                                  at android.app.ActivityThread.deliverResults(ActivityThread.java:3700)
                                                                                                  at android.app.ActivityThread.handleSendResult(ActivityThread.java:3747) 
                                                                                                  at android.app.ActivityThread.access$1400(ActivityThread.java:153) 
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5432) 
                                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735) 
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

**Comment by LeChauvet** [comment]
I give up using cursor and get the selectedImagePath by using the clause like this and it works:
String selectedImagePath = selectedImageUri.getPath();
